### ISSUE TITLE
Release schedule for updating packages

### ISSUE THREAD

**Issue by bp88** [macadmins/python#10]
Sooner or later it may come up that a module or two will get updated and therefore someone may request an update to have new packages released.

If we look at the following schedule for 3.8: https://www.python.org/dev/peps/pep-0569/#schedule
3.8.0 final: Monday, 2019-10-14
3.8.1: Wednesday, 2019-12-18
3.8.2: Monday, 2020-02-24
3.8.3: Wednesday, 2020-05-13
3.8.4: Monday, 2020-07-13 (expected)

That seems to be every 2-3 months.

For reference on 3.7: https://www.python.org/dev/peps/pep-0537/#release-schedule
3.7.0 final: 2018-06-27
3.7.1 final: 2018-10-20
3.7.2 final: 2018-12-24
3.7.3 final: 2019-03-25
3.7.4 final: 2019-07-08
3.7.5 final: 2019-10-15
3.7.6 final: 2019-12-18
3.7.7 final: 2020-03-10

About every ~3 months.

I'm proposing that this project follow the release schedule for the latest Python version + 2 weeks to generate new packages. The hope is that this would allow any potential issues to ideally get resolved if anything unexpected comes up that didn't already come up during the Python release candidate testing.

**Comment by erikng** [comment]
@bp88 do you plan on contributing in a meaningful way to making this a possibility? There would need to be a lot of automation created, and this doesn't address the other elephant in the room: 3rd party library updates.

Apple has not updated Python except for small yearly changes.

I will be honest. I do not plan on accepting that role and responsibility for the macadmin community. If someone wants to take up that mantle and also shine the bat signal when needed, great.

If people deem that they want this schedule but no one wants to help, perhaps archiving this project would be a more sane solution.

**Comment by natewalck** [comment]
Maybe the build job can be setup with a schedule? Do a new build every N days? Change logs won't be happening, but I don't see a good way to do this otherwise.

**Comment by grahamgilbert** [comment]
You could use dependabot for the packages https://help.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically

**Comment by bfreezy** [comment]
There is also https://pyup.io/ which is free for open source projects.

**Comment by erikng** [comment]
> Maybe the build job can be setup with a schedule? Do a new build every N days? Change logs won't be happening, but I don't see a good way to do this otherwise.

After experimenting with GitHub actions over the past few hours this is indeed possible, however since the build scripts take environmental variables, we will likely need to initially create a new `build.yaml` file for each version of python. I think this will be pretty easy to do and I will likely test my theory soon.

**Comment by erikng** [comment]
https://github.com/macadmins/python/commit/35332aaae44bc11eb7645b2dd9451092aa2ffa12

It worked. Now building Python 3.8.2 and Python 3.8.3 releases

**Comment by erikng** [comment]
I am going to close this ticket, but it will now be trivial to support this and anyone can send a PR to build whatever version you want to build once it's publicly available.

This doesn't address the libraries themselves being updated, but that will be tracked at https://github.com/macadmins/python/issues/12
