### ISSUE TITLE
Document how to utilize the framework

### ISSUE THREAD

**Issue by erikng** [macadmins/python#3]
Documentation needs to be written to address how to use the framework with a tool.

**Comment by ygini** [comment]
How to use but also how to install it. Documentation must be explicit about:
- it’s a shared package that can already be there
- upgrade is allowed and expected
- downgrade must not happen
- everything must happen in virtual env when installing new modules

**Comment by erikng** [comment]
@ygini please check the readme and see what you think now

**Comment by ygini** [comment]
Here is some comments on a first read:
- the link to File System Basic does not have any info about `SystemFrameworks` folder
- really good to have used `Versions/3.8` 
- add a small howto about virtual env and how to create one, with some smart example (like in `/Library/Application Support/com.example.app/python3_venv`)
- add comments about how to bundle this as a raw package in distribution package for any apps that want to use it

**Comment by gregneagle** [comment]
Using Python virtual environments seems out of scope for this project. Even if they are good practice, they are certainly not required, and there’s no reason to scare off admins that just want to get a simple script running.

**Comment by ygini** [comment]
@gregneagle documentation is all about avoiding people to hurt themselves with your product, to avoid complains when you will erase everything with your next version.

So even if it's not needed for basic script that does not require dependencies, it will be at some point. And there it will be really interesting if we encouraged every future users to use the product according to our mindset, to be as much as we can futureproof.

**Comment by gregneagle** [comment]
Then the "documentation" as part of this project should be:

As always, virtual environments are recommended for Python projects of any complexity. Learn more here: https://virtualenv.pypa.io/en/latest/ and https://docs.python-guide.org/dev/virtualenvs/

And nothing more. It's really not this tool's job to repeat and maintain documentation like that.

**Comment by natewalck** [comment]
My opinion here mirrors Greg's. 

This should provide a reference python implementation for MacAdmins and nothing more. If a specific library is needed, having links out to virtual envs makes a lot of sense (or `pex` files or pyinstaller bundles). 

I think those are a better solution for shipping libraries than polluting the managed python framework. We should also be very clear in the documentation that people should not pip install to this python unless they enjoy pain.

**Comment by grahampugh** [comment]
Have you considered using the wiki for the documentation?

**Comment by erikng** [comment]
Yes. Let me turn it on.

**Comment by captam3rica** [comment]
Any thoughts for having a disclaimer or list of items that speak to what this repo is not? 

Some thoughts that I had ...

- Does not contain everything ...
- is not intended to cover all scenarios ...
- Not designed to replace py3 package from python.org

**Comment by erikng** [comment]
Care to elaborate? Define everything.

Thanks,
Erik Gomez
________________________________

**Comment by captam3rica** [comment]
yeah your right. Defining everything is probably not the best idea ... 

I think, after looking at the Notes section, it highlights some of the areas that this repo is not intended to handle.

**Comment by erikng** [comment]
I personally think the documentation is sufficient for this version and as others said, some of the suggestions here do not necessarily make sense for this project.

That said, the wiki is now open and PR's are welcome. For now I will be closing this issue.
