### ISSUE TITLE
Could not find python

### ISSUE THREAD

**Issue by Supergoof** [macadmins/python#42]
Seems like Apple changed the path to python installed with xcode, so I had to change the version of relocatable-python used in build_python_framework_pkgs.zsh line 9, as this is fixed in that version.

https://github.com/gregneagle/relocatable-python/commit/0184e8b43f1ecde050b07feb1761fac2f7ce0c5c

`RP_SHA="06b3052afe49c400aa4196f2aada15c0992e3725"` --> `RP_SHA="0184e8b43f1ecde050b07feb1761fac2f7ce0c5c"`

**Comment by erikng** [comment]
Thanks, I'll be looking at a lot of this soon.
