### ISSUE TITLE
Abandoned Project? Lacking Security Updates

### ISSUE THREAD

**Issue by dwbotsch** [macadmins/python#43]
Hi.
Doesn't look like this has been updated since February. And just this September, there were security updates to Python per https://pythoninsider.blogspot.com/2022/09/python-releases-3107-3914-3814-and-3714.html .

Looks like it's stuck at Python 3.10.2.80694 and not the current 3.10.7 .

So is this project abandoned?

thanks.

**Comment by natewalck** [comment]
Definitely not abandoned. Community support is key to maintaining projects like this. Please file a Pull Request for the impacted Python version/libraries to get this updated.

**Comment by erikng** [comment]
Yes, if you have the knowledge and concern please send a pull request. My priorities are not always going to be aligned with my ability to maintain projects that hundreds or thousands of users install.

it's untenable long term for one person to support projects like this without others helping.

**Comment by erikng** [comment]
I'll be addressing this soon.

**Comment by erikng** [comment]
https://github.com/macadmins/python/releases/tag/v3.9.13.80712
https://github.com/macadmins/python/releases/tag/v3.10.9.80716
https://github.com/macadmins/python/releases/tag/v3.11.1.80716
