### ISSUE TITLE
Release version has different signing authority

### ISSUE THREAD

**Issue by jazzace** [macadmins/python#54]
For those of us automating download of this project's releases (in my case, with AutoPkg), the signing authority of the current release (3.10.9.80716) is different than the pre-release versions. This prevents me from checking the signing authority automatically. It would be great if you could replace the current pkg installer for 3.10.9.80716 with one signed by Mac Admins Open Source. Of course, if you are going to release 3.11 or 3.12 shortly, the question is moot.

**Comment by natewalck** [comment]
I believe `3.10.9.80716` was the last version signed by the old code signing cert. Everything after that will be the proper Mac Admins Open Source one.

**Comment by jazzace** [comment]
Yes. I'm just saying that I can't write a working AutoPkg recipe right now that lets users choose either the current release or the latest prerelease. If that problem is going away soon, then no problem. If it's going to be a while, it would be nice to have that 3.10 package updated with the new signing cert.

**Comment by natewalck** [comment]
> Yes. I'm just saying that I can't write a working AutoPkg recipe right now that lets users choose either the current release or the latest prerelease. If that problem is going away soon, then no problem. If it's going to be a while, it would be nice to have that 3.10 package updated with the new signing cert.

Got it. I don't think we have any plans for re-releasing 3.10.9.80716. It would be better to promote the updated 3.10 to release. 

I'm not sure if its 100% ready to go...if you don't mind putting it through its paces and giving feedback, it would help us get it out the door faster.

**Comment by jazzace** [comment]
Got it. Based on the status of 3.10, I will test 3.11 and report back.

**Comment by erikng** [comment]
I'm very sick right now but my testing from last week looked promising and I found nothing worrying on all four versions. 

Definitely would appreciate more testers.

**Comment by erikng** [comment]
I'm confident in the releases now and have marked all of the 3.x.x.80740 releases as non pre-release and made 3.12.1.80740 the latest release.
