### ISSUE TITLE
Changing managed_python3 from a symlink to a script breaks some uses

### ISSUE THREAD

**Issue by jazzace** [macadmins/python#55]
For one particular script I have been using, I made the shebang into `#!/usr/local/bin/managed_python3` to direct it to this python installation. In the 3.10.2 release, that path is a symlink to the current executable. In the latest 3.11.x release, this is now a script. This seems to break the use of that path in a shebang, as the script in question can no longer load any modules (Error message: `import: command not found`). There are certainly other ways I can point that script in the proper direction, but this new method of redirecting to the current python breaks the shebang method.

**Comment by erikng** [comment]
Yep. There's nothing we can do due to the upstream change in python that then impacts relocatable python 3.11 and 3.12. You will have to update your shebang to use the proper path.

**Comment by erikng** [comment]
@jazzace can you try https://github.com/macadmins/python/releases/tag/v3.12.1.80741 ?

**Comment by jazzace** [comment]
Initial testing shows that it works. 🎉 I have a side issue that has cropped up with the GUI tool that runs it, but running the Python script from the command line with `#!/usr/local/bin/managed_python3` as the shebang seems to work.

**Comment by erikng** [comment]
What is that issue?

**Comment by jazzace** [comment]
Funny thing. The error was actually related to PPPC once I dug in deeper. (I had someone else help me with testing our GUI tool but they copied one file to the Desktop, which is what triggered the PPPC problem.)

**Comment by jazzace** [comment]
Closing the issue.

**Comment by erikng** [comment]
Awesome. Thanks for testing and confirming.
