### ISSUE TITLE
What path should we use?

### ISSUE THREAD

**Issue by erikng** [macadmins/python#7]
bp
```
Why /Library/frameworks?
Why not /Library/Frameworks ?
I know that the official Python lives in /Library/Frameworks  when it’s installed so I’m guessing the intent was to avoid conflicts there. But if so, why try to use a path that seems like it can create confusion where the difference is literally an uppercase “f”?
Obviously no one is forced to use this. However I am curious at the rationale there and just wanted to bring up discussion of it. It may be too late though.
I was thinking of this recently and was going to/will go forward with a different path of my own:
/opt/mgmt
and under that /opt/mgmt/Frameworks  and /opt/mgmt/bin
(alternatively it could be /opt/mgmt/frameworks if you want to follow in the unix convention of lower case characters for the paths)
My rationale:
It’s generic. I can’t convince everyone to do the same, but it sure would be nice if someone decided on something generic enough that could be used anywhere. It might at least might encourage others to use the same path.
It’s a short acronym (e.g. mgmt) that insinuates that it’s for management of the computer.
It’s not commonly used by popular packaging tools like homebrew and won’t conflict with MacPorts.
It’s not part of $PATH which decreases the chances there’s a conflict if a user installs their own version of Python 3.
It allows me to create a somewhat short symbolic link: /opt/mgmt/bin/python3
/opt is protected in macOS 10.15 because the root volume is read-only. To be fair, /usr/local is also protected by System Integrity Protection, though the contents under it are not.
/opt is hidden in macOS 10.15.
The only caveat here is that on pre-10.15 the opt path would probably need to have be hidden using chflags which mean having to use a postinstall script in a pkg to hide the folder on pre-10.15 systems.



Looks like since my comment, a commit was made to change the directory from /Library/frameworks/Python.framework  to /Library/SystemFrameworks/Python3.framework that at least solves the concern on confusion I raised earlier. The note pointing to Apple documentation on File System basics doesn’t quite answer why that path over any other directory, but that I guess becomes a matter of preference. And the folder name makes it seem like /Library/SystemFrameworks is referring to /System/Library/Frameworks but it’s not. Again, I’d still vote for my suggestion that I raised earlier of /opt/mgmt. If we want to point to historical context, /opt uses this path specifically for other application system packages and packages not part of the Operating System distribution, but provided by an independent source.
But I want to bring up two other points:
1. I feel like to make it truly useful you have to address the other issue that comes with adapting this tool which is that scripts when shared tend to be written with a she-bang. Yes, I’m aware you can write scripts without a she-bang but I don’t think that’s a trend that will take off and nor should it. That means either:
You force people to refer to !#/Library/SystemFrameworks/Python.framework/Versions/3.8/bin/python3
You opt to use another directory to drop a symbolic link that’s a little shorter and not part of $PATH for reference in your she-bang.
Note: I’m making the assumption here that no admin would want their managed Python to be a part of $PATH due to the conflicts that creates with potential devs or other tools.
I don’t see the former happening. It’s too long. The latter hasn’t been addressed and I think it needs to be. /usr/local/bin would be out of the question as it would be whether dev tools would go to in the first place plus it is part of $PATH.
2. There are 4 releases. No Customization > Minimal > Recommended > Opinionated. Each is respectively a subset of the next. To err on the sake of simplicity, would it make more sense to get it down to two flavors? Minimal and Opinionated. Here’s my rationale
Minimal should be self-explanatory. It covers what the original intent of the Relocatable Python covers.
If someone wants plain Python for managing their Macs, they can very well just rely on the Xcode Command Line Tools which automatically install Python 3.
The difference between Recommended and Opinionated is 10 additional modules:
arrow.txt
atomicwrites.txt
boto.txt
funcsigs.txt
pytest.txt
pytest-docker.txt
python-dotenv.txt
rsa.txt
slacker.txt
Sphinx.txt

Since Recommended is just a subset of Optional in this case, wouldn’t it be simpler to just make Opinionated the actual “recommended” download. Whatever objections the audience for “Recommended” would have would just be solved by them pushing out their own Python.

I’m assuming, but could be wrong, that the goal of this is to create a Python that admins can push out and to create a standard that admins can rely on that would make it easier when sharing scripts among the community. With those goals in mind, I think it would be worth addressing the points above and that it would help getting adoption. And if they already have been discussed and this is what the final decision looks like, it might be worth pointing them out in more clarity in the repo.
```

grahamrpugh
```
Indeed.
I personally don’t really like the idea of SystemFrameworks . System in paths is generally reserved for stuff from Apple.
I already put “management” stuff in /Library/Management and if we have to distribute a python for management purposes, I’d probably put it there.
```

macmule
```
Just to add yet another opinion, I’d use /Library/Application Support/macadmins/ & put stuff under there.. i don’t think you’ll ever appease all the people with this choice 
```

**Comment by erikng** [comment]
Some immediate thoughts `/Library/Application Support` was a path I intended to use internally when we shipped our own python, only to realize there is a 25 year old bug with shebangs, that you cannot have spaces in the path. I want a stable path that is not in `/usr/local/bin` since anyone can kill it.

After consideration last night, I determined `paths.d` was not sufficient as it would increase the chances of:
1. users using it and getting annoyed when something doesn't work
2. it bringing in `pip` and other binaries that would also increase the chances of point 1 

The path isn't set in stone, but I chose `/Library/SystemFrameworks` as there is no known software, open source or otherwise that use this location and certain python user didn't see any issues with it.

My apprehension about `/opt` is two fold as well:
1. `/opt` is used by other tools, including developer tools. Sometimes developers rage quit and delete /opt to start all over. It would be a shame if all your tooling died because of a user's ignorance
2. Apple is increasingly putting walls up in UNIX paths. `/Library` is distinct to Apple, so I felt it would make more sense there.

**Comment by gregneagle** [comment]
I find the complaint "but it makes the shebang line too long" an unconvincing one. It's not like you have to type it all the time, and copy-and-paste has been a a thing for 35+ years. If a local admin wants to make a symlink in a shorter path, I think that's up to them, but if _you_ do it, I think you'll encounter the exact same issues you detail as far as the location of the framework.

**Comment by erikng** [comment]
I _think_ I have come up with an approach that addresses that aspect, but I do agree that it increases support.

`/usr/local/bin/python3.framework` is now created for purely ease-of-use with interactive scripts/debugging purposes, but I wouldn't rely on it long term since it's in `/usr/local/bin`. I have seen countless developers blow away everything in this folder and spent time writing circular dependency logic within our CM tool to handle that. I imagine this will work only for macadmins who are playing on their own machine, but not for production use.

`/Library/SystemFrameworks/Python3.framework/python3` is far more important though as it points to `/Library/SystemFrameworks/Python3.framework/Versions/3.8/bin/python3.8`. When Python ships 3.9 the path will change to `/Library/SystemFrameworks/Python3.framework/Versions/3.9/bin/python3.9` so if all of your shebangs point to the 3.8 bin, everything would break. I encountered this when building InstallApplications (and actually have not solved it until earlier today in this repo. I need to backport the fix).

A stable path through the lifecycle of Python3 (and Python4+) will be paramount to reducing support burden for the maintainers of this repository.

**Comment by gregneagle** [comment]
The Python interpreter isn't available at `/Library/SystemFrameworks/Python3.framework/Versions/Current/bin/python3` ?

_That_ would be a more standard solution to providing a stable path. (Standard in that it follows the convention of other frameworks)

**Comment by gregneagle** [comment]
FWIW:
```
$ ls -al /usr/local/munki/Python.framework/Versions/Current/bin/python3
lrwxr-xr-x  1 root  wheel  9 May 19 09:29 /usr/local/munki/Python.framework/Versions/Current/bin/python3 -> python3.7```

**Comment by bp88** [comment]
I think these are all very sound reasons and definitely should be included in the docs as the repo gets fleshed out.

As for `/opt`:
1. I wouldn’t trust the integrity of any directory on its own. I'd say it would be the job of the management agent to check for the integrity of whatever path is chosen and remediate accordingly.
2. I've not seen too many tools make use of `/opt`. The only one that I've encountered has been MacPorts which makes use of `/opt/local`. And Cisco AnyConnect once upon a time when I had to deploy that app. I'm not sure if it still makes use of that path. What other tools have you seen make use of this? This is the path that I'm using to use in our environment so it'd be good to know specifics.
3. `/opt` is under the root volume and therefore cannot be wiped so it's afforded that little bit of extra protection by macOS in 10.15. It's contents are another story, but that's the case with any directory (see point 1 regarding remediation). I think the fact that Apple made the directory in 10.15 a part of the OS and chose to leave it blank says that they acknowledge it's a conventional path that is used by third party applications/tools and they have no intention of using it themselves.

As for `/usr/local/bin/` as a place for a python3 symlink, I'd be against it. It would be part of $PATH. Then there's the issue of `homebrew` and the amount of third party tools that use that path.

Basically I'm seeking two goals here: simplicity and avoiding confusion.
1. `/opt/mgmt/bin/python3` is 21 characters vs `/usr/bin/python3` which is 16. This makes it easier to remember when writing out scripts.  `/Library/SystemFrameworks/Python3.framework/python3` is 51 characters. There doesn't seem to be anything conventional about such a long shebang.
2. When I'm in Terminal, I'm used to searching the 3 letter directories under the root volume to look for certain tools. It'll be much quicker to remember and to search under `/opt` which is empty by default than `/Library`. I try to avoid making modifications to Terminal so it's easier to jump between computers when providing support.
3. `/Library/SystemFrameworks` makes it seem like this is something from Apple.

If we must choose something in `/Library`, then I'd propose 2 alternatives:
- `/Library/Management` with the sub-directory of `Frameworks`.
Or
- `/Library/ManagedFrameworks` which would limit the folder to only other potential Frameworks that are managed.

I'd also propose that whatever path is chosen get the `hidden` flag to hide it from Finder.

And lastly, whatever symlink is used, should point to `...../Python3.framework/Versions/Current/bin/python3` It avoids having to worry about the version (e.g. 3.8 to 3.9, etc.).

**Comment by gregneagle** [comment]
`/Library/ManagedFrameworks`
`/Library/SystemFrameworks`

Your suggestion is TWO CHARACTERS LONGER!

**Comment by bp88** [comment]
Well my suggestion for `/Library/ManagedFrameworks` is only if we insist in having to use `/Library`
At that point, then my problem is with the naming of the folder and what message it sends. `SystemFrameworks` sounds like something from Apple. `ManagedFrameworks` sounds like something that's managed.

**Comment by gregneagle** [comment]
Perhaps that's the point.
Perhaps a user might be less likely to rip out /LIbrary/SystemFrameworks than tear out that crap the IT department puts in /Library/Management or /Library/ManagedFrameworks...

**Comment by erikng** [comment]
Greg's point was indeed my rationale for the name.

Thanks,
Erik Gomez
________________________________

**Comment by bp88** [comment]
I don't think we should intentionally try to mislead through folder naming. The intent of the folder should be clear through it's name.

Any remediation you need to do, should be done through the management agent if that's the concern.

**Comment by erikng** [comment]
/Library/ManagedFrameworks is a great idea. Chef and Puppet use /opt and I can tell you it would be an issue here as people try to destroy that path quite often.

**Comment by natewalck** [comment]
Either `/Library/SystemFrameworks` or `/Library/ManagedFrameworks` works. I think I prefer `ManagedFrameworks` only because `System` implies Apple these days even if its not something Apple actually creates/cares about.

**Comment by grahampugh** [comment]
I would not object to `/Library/ManagedFrameworks`. We may well have to distribute managed ruby and perl, and perhaps others, and that seems a reasonable catch-all.

**Comment by bp88** [comment]
Thanks for sharing that. I'm not familiar with Chef or Puppet so it's not something I would have had experience with, but it makes perfect sense to avoid the directory in which your management agent lives.

**Comment by keeleysam** [comment]
anything under `/Library` is fine, for it is where things like this belong on macOS.

**Comment by erikng** [comment]
If anyone objects to /L/MF speak now.

**Comment by rodchristiansen** [comment]
+1 for `/Library/ManagedFrameworks` as there will be others built-in 3rd party frameworks removed by Apple we’ll eventually need.

**Comment by erikng** [comment]
> The Python interpreter isn't available at `/Library/SystemFrameworks/Python3.framework/Versions/Current/bin/python3` ?
> 
> _That_ would be a more standard solution to providing a stable path. (Standard in that it follows the convention of other frameworks)

Greg is correct here. We can populate `/usr/local/bin/managed_python3` for easy interactive use, but the stable path for shebangs will be `/Library/ManagedFrameworks/Python3.framework/Versions/Current/bin/python3`

Open to other names for the interactive python3.
- `python3.framework`
- `managed_python3`
- `managedpython3`

**Comment by bp88** [comment]
I would prefer that no symlink be provided in `/usr/local/bin/`. I do not want it to be available in everyone's $PATH.

**Comment by erikng** [comment]
We can discuss that at https://github.com/macadmins/python/issues/13

Closing this since I think we have solved the path issue.
